spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/javohir
    username: javohir
    password: JavohBek2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  mail:
    host: smtp.gmail.com
    port: 587
    username: zhavokhir5515@gmail.com
    password: unno nron lefx zyal
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

jwt:
  secret: K7j3F8vM9@pZ#s1R4tLw$yQn&UcXeGbA

logging:
    level:
      org.springframework.security: DEBUG
      org.springframework.web.filter: DEBUG
      # Можно указать пакет вашего приложения, например:
      uz.mini_market.market: DEBUG

